# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='新闻分类')),
            ],
            options={
                'db_table': 'news_Category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
                ('index_img_url', models.CharField(max_length=256, null=True, verbose_name='新闻图片')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('digest', models.CharField(max_length=128, verbose_name='描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Category')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'news_News',
            },
        ),
        migrations.CreateModel(
            name='User_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.News')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'news_User_Collection',
            },
        ),
    ]
