# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190411_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.News'),
        ),
    ]
