# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20190416_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_delete',
            field=models.IntegerField(default=0, verbose_name='是否删除'),
        ),
    ]
