# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authername', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('_password', models.CharField(max_length=256, verbose_name='密码')),
                ('avatar_url', models.CharField(max_length=256, null=True, verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.IntegerField(default=1, verbose_name='权限')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'news_Auther',
            },
        ),
    ]
