# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('nick_name', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('avatar_url', models.CharField(max_length=256, null=True, verbose_name='头像')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'news_User',
            },
        ),
        migrations.CreateModel(
            name='User_Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('followed_id', models.IntegerField()),
            ],
            options={
                'db_table': 'news_User_Fans',
            },
        ),
    ]
